"use strict";
// Regenerate the root landing page (index.html) by scanning artifacts/.
// Each immediate subfolder of artifacts/ that contains an index.html becomes
// a listed artifact. The card title is read from that file's <title>, the
// blurb from its <meta name="description"> if present. No dependencies.
//
//   node scripts/generate-index.js
//
// Re-run this whenever you add a new artifact under artifacts/<slug>/index.html.

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const artifactsDir = path.join(root, "artifacts");

function read(file) {
  try { return fs.readFileSync(file, "utf8"); } catch (e) { return ""; }
}

function pick(html, re, fallback) {
  const m = html.match(re);
  return m ? m[1].trim() : fallback;
}

// human-friendly title from a slug, e.g. "drift-lock" -> "DRIFT LOCK"
function fromSlug(slug) {
  return slug.replace(/[-_]+/g, " ").toUpperCase();
}

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const artifacts = fs.readdirSync(artifactsDir, { withFileTypes: true })
  .filter(d => d.isDirectory())
  .map(d => d.name)
  .filter(slug => fs.existsSync(path.join(artifactsDir, slug, "index.html")))
  .sort()
  .map(slug => {
    const html = read(path.join(artifactsDir, slug, "index.html"));
    return {
      slug: slug,
      href: "artifacts/" + slug + "/index.html",
      title: pick(html, /<title>([^<]*)<\/title>/i, fromSlug(slug)),
      desc: pick(html, /<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i, "")
    };
  });

const cards = artifacts.map(a => `      <a class="card" href="${esc(a.href)}">
        <div class="name">${esc(a.title)}</div>
        ${a.desc ? `<div class="desc">${esc(a.desc)}</div>` : ""}
        <div class="go">Open &rarr;</div>
      </a>`).join("\n\n");

const page = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Pipeline Artifacts</title>
<!-- This file is generated by scripts/generate-index.js. Edit that, not this. -->
<style>
  *{box-sizing:border-box;}
  html,body{height:100%;}
  body{
    margin:0;
    background:#0c0c0e;
    color:#e8e6e6;
    font-family:"Helvetica Neue",Helvetica,Arial,system-ui,sans-serif;
    min-height:100vh;
    display:flex;
    align-items:center;
    justify-content:center;
    padding:40px 22px;
  }
  .wrap{width:100%;max-width:560px;text-align:center;}
  .kicker{
    font-size:11px;letter-spacing:0.4em;text-transform:uppercase;
    color:#6f6c72;margin-bottom:14px;padding-left:0.4em;
  }
  h1{font-weight:400;font-size:clamp(26px,6vw,38px);margin:0 0 8px;letter-spacing:0.01em;}
  .sub{color:#8a878d;font-size:14px;margin:0 0 44px;}
  .cards{display:flex;flex-direction:column;gap:16px;}
  a.card{
    display:block;text-decoration:none;text-align:left;
    padding:22px 24px;border:1px solid rgba(255,255,255,0.10);
    border-radius:14px;background:rgba(255,255,255,0.02);
    transition:border-color 200ms ease, transform 200ms ease, background 200ms ease;
  }
  a.card:hover{
    border-color:rgba(255,255,255,0.28);transform:translateY(-2px);
    background:rgba(255,255,255,0.04);
  }
  .name{font-size:18px;letter-spacing:0.04em;margin-bottom:6px;color:#e8e6e6;}
  .desc{font-size:13px;color:#9a979d;line-height:1.5;}
  .go{font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:#6f6c72;margin-top:12px;}
  footer{margin-top:40px;font-size:11px;color:#56545a;letter-spacing:0.08em;}
</style>
</head>
<body>
  <main class="wrap">
    <div class="kicker">Pipeline Artifacts</div>
    <h1>${artifacts.length} single-screen ${artifacts.length === 1 ? "thing" : "things"}.</h1>
    <p class="sub">Pick one.</p>

    <div class="cards">
${cards}
    </div>

    <footer>generated from artifacts/</footer>
  </main>
</body>
</html>
`;

fs.writeFileSync(path.join(root, "index.html"), page);
console.log("Wrote index.html with " + artifacts.length + " artifact(s):");
artifacts.forEach(a => console.log("  - " + a.title + "  ->  " + a.href));
